
cXY = [25, 5; ...
    25, 25; ...
    25, 45; ...
    45, 5; ...
    45, 25; ...
    45, 45];

centroids = dentist.utils.Centroids(cXY(:,1), cXY(:,2));

spotXYpos = [    -2    -2;...
    -1     0;...
     0    -2;...
    -2    -1;...
     1    -2;...
     0    -2;...
    -2     2;...
     2    -1;...
    -2     1;...
    -1     3];

centroidAssignment = [2,1,1,4,1,1,2,4,2,2];
spotXYpos = spotXYpos + cXY(centroidAssignment,:);

%%
spots = dentist.utils.ChannelArray({'cy'});
spots = spots.setByChannelName(
spotToCentroidMaps = dentist
