function tools = launchGUI(exonChannelName, intronChannelName, varargin)

tools = improc2.launchImageObjectBrowsingTools(varargin{:});
objectHandle = tools.objectHandle;
navigator = tools.navigator;

dataNodeLabel = [exonChannelName, intronChannelName, ':TxnSites'];
nodeDataBasedTxnSitesCollection = improc2.txnSites.IntronExonTranscriptionSitesCollection(tools.objectHandle,...
    dataNodeLabel);

imageHolders = struct();

imageHolders.exon = ...
    improc2.utils.ImageHolderFromImageObjectHandle(objectHandle, ...
    exonChannelName, ...
    'improc2.nodeProcs.RegionalMaxProcessedData');

imageHolders.intron = ...
    improc2.utils.ImageHolderFromImageObjectHandle(objectHandle, ...
    intronChannelName, ...
    'improc2.nodeProcs.RegionalMaxProcessedData');

imageHolders.dapi = ...
    improc2.utils.ImageHolderFromImageObjectHandle(objectHandle, ...
    'dapi', ...
    'improc2.nodeProcs.DapiProcessedData');

improc2.txnSites.launchIntronExonTxnSiteGUI(navigator, nodeDataBasedTxnSitesCollection, imageHolders)

improc2.launchAnnotationsGUI(tools.annotations)

navigator.addActionBeforeMoveAttempt(nodeDataBasedTxnSitesCollection,...
    @flagAsReviewed);
    