function [Hs] = layOutNaviPanelGUI()
    
    backgColor = [0.247 0.247 0.247];
    
    Hs.figH = figure('Position',[250 100 800*0.33 554*0.26],...
        'NumberTitle','off',...
        'Name','improc2.ThresholdInspectorGUI',...
        'Resize','on',...
        'Toolbar','none',...
        'MenuBar','none',...
        'Color',backgColor,...
        'Visible','off');
    
    set(Hs.figH, 'Visible', 'on');
    
    
    Hs.naviPanel  = uipanel('Parent',Hs.figH,...
        'Units','normalized',...
        'Position',[0.05 0.05 0.9 0.9],...
        'BackgroundColor',[0.929 0.929 0.929]);
    
    
    Hs.goodCheck = uicontrol('Parent',Hs.naviPanel,...
        'Style','checkbox',...
        'Units','normalized',...
        'Position',[0.559 0.803 0.403 0.181],...
        'String','Good Object',...
        'Value',0);
    Hs.prevObj = uicontrol('Parent',Hs.naviPanel,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',[0.525 0.622 0.216 0.150],...
        'String','Prev',...
        'FontSize',12,'FontWeight','bold');
    Hs.nextObj = uicontrol('Parent',Hs.naviPanel,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',[0.758 0.622 0.216 0.150],...
        'String','Next',...
        'FontSize',12,'FontWeight','bold');
    
    Hs.countsLabel = uicontrol('Parent',Hs.naviPanel,'Style','text',...
        'String','Spot Count',...
        'Units','normalized',...
        'Position',[0.05 0.55 0.4 0.157],...
        'FontSize',12,'FontWeight','bold');
    Hs.countsDisplay = uicontrol('Parent',Hs.naviPanel,'Style','text',...
        'String','0',...
        'Units','normalized',...
        'Position',[0.05 0.4 0.4 0.157],...
        'FontSize',12,'FontWeight','bold');
    
    Hs.fileLabel = uicontrol('Parent', Hs.naviPanel, ...
        'Style','text',...
        'String',sprintf('File:\n/ '),...
        'Units', 'normalized', ...
        'Position', [0.025 0.1 0.216 0.25], ...
        'FontSize', 12, 'FontWeight', 'bold');
    Hs.goToArray = uicontrol('Parent',Hs.naviPanel,...
        'Style','edit',...
        'Units','normalized',...
        'Position',[0.275 0.1 0.216 0.25],...
        'FontSize',12);
    Hs.objectLabel = uicontrol('Parent', Hs.naviPanel, ...
        'Style','text',...
        'String',sprintf('Obj:\n/ '),...
        'Units', 'normalized', ...
        'Position', [0.525 0.1 0.216 0.25], ...
        'FontSize', 12, 'FontWeight', 'bold');
    Hs.goToObj = uicontrol('Parent',Hs.naviPanel,...
        'Style','edit',...
        'Units','normalized',...
        'Position',[0.775 0.1 0.216 0.25],...
        'FontSize',12);    
end
