display('improc2.extraction.AnnotationDataExtractor_test')
improc2.extraction.AnnotationDataExtractor_test;
display('improc2.extraction.DataExtractorFromAllObjects_test')
improc2.extraction.DataExtractorFromAllObjects_test;
display('improc2.extraction.ObjectHandleDataExtractor_test')
improc2.extraction.ObjectHandleDataExtractor_test;
display('improc2.extraction.ProcessorDataExtractor_test')
improc2.extraction.ProcessorDataExtractor_test;
display('improc2.fitting.fit2dGaussiansToImage_test')
improc2.fitting.fit2dGaussiansToImage_test;
display('improc2.fitting.fitSpotPositionsThenRefineForAmplitude_test')
improc2.fitting.fitSpotPositionsThenRefineForAmplitude_test;
display('improc2.fitting.Gaussian2dSpot_test')
improc2.fitting.Gaussian2dSpot_test;
display('improc2.fitting.GaussianSpotFitter_test')
improc2.fitting.GaussianSpotFitter_test;
display('improc2.processing.fitGaussiansToSpots_test')
improc2.processing.fitGaussiansToSpots_test;
display('improc2.processing.ImageObjectsProcessor_test')
improc2.processing.ImageObjectsProcessor_test;
display('improc2.procs.aTrousRegionalMaxProcData_test')
improc2.procs.aTrousRegionalMaxProcData_test;
display('improc2.procs.DapiProcData_test')
improc2.procs.DapiProcData_test;
display('improc2.procs.ProcessorData_test')
improc2.procs.ProcessorData_test;
display('improc2.procs.RegionalMaxProcData_test')
improc2.procs.RegionalMaxProcData_test;
display('improc2.procs.SNPColocalizerData_test')
improc2.procs.SNPColocalizerData_test;
display('improc2.procs.TransProcData_test')
improc2.procs.TransProcData_test;
display('improc2.procs.TwoStageGaussianSpotFitProcessorData_test')
improc2.procs.TwoStageGaussianSpotFitProcessorData_test;
display('improc2.thresholdGUI.CompositeImageMaker_test')
improc2.thresholdGUI.CompositeImageMaker_test;
display('improc2.thresholdGUI.launchThresholdGUICore_test')
improc2.thresholdGUI.launchThresholdGUICore_test;
display('improc2.thresholdGUI.layOutImageInspectionGUI_test')
improc2.thresholdGUI.layOutImageInspectionGUI_test;
display('improc2.thresholdGUI.layOutStarSearchGUI_test')
improc2.thresholdGUI.layOutStarSearchGUI_test;
display('improc2.thresholdGUI.SliceExclusionMouseInterpreter_test')
improc2.thresholdGUI.SliceExclusionMouseInterpreter_test;
display('improc2.thresholdGUI.SpotsPerSliceDisplayer_test')
improc2.thresholdGUI.SpotsPerSliceDisplayer_test;
display('improc2.utils.addRowToCellTable_test')
improc2.utils.addRowToCellTable_test;
display('improc2.utils.AnnotationsHolderForLegacyimage_object_test')
improc2.utils.AnnotationsHolderForLegacyimage_object_test;
display('improc2.utils.applyATrousImageFilter_test')
improc2.utils.applyATrousImageFilter_test;
display('improc2.utils.ArrayNumberTextBox_test')
improc2.utils.ArrayNumberTextBox_test;
display('improc2.utils.buildTypeCheckedValuesFromStruct_test')
improc2.utils.buildTypeCheckedValuesFromStruct_test;
display('improc2.utils.ContrastedScaledImageHolder_test')
improc2.utils.ContrastedScaledImageHolder_test;
display('improc2.utils.convertChoicesToString_test')
improc2.utils.convertChoicesToString_test;
display('improc2.utils.convertValueToString_test')
improc2.utils.convertValueToString_test;
display('improc2.utils.cropImageToObjBoundingBox_test')
improc2.utils.cropImageToObjBoundingBox_test;
display('improc2.utils.DependencyRunner_test')
improc2.utils.DependencyRunner_test;
display('improc2.utils.displayDescriptionOfHandleObject_test')
improc2.utils.displayDescriptionOfHandleObject_test;
display('improc2.utils.displayDescriptionOfNamedValuesAndChoices_test')
improc2.utils.displayDescriptionOfNamedValuesAndChoices_test;
display('improc2.utils.displayFullMethodDescriptions_test')
improc2.utils.displayFullMethodDescriptions_test;
display('improc2.utils.doNothing_test')
improc2.utils.doNothing_test;
display('improc2.utils.ExtensiblePushButtonGroup_test')
improc2.utils.ExtensiblePushButtonGroup_test;
display('improc2.utils.FieldsBasedItemCollectionHandle_test')
improc2.utils.FieldsBasedItemCollectionHandle_test;
display('improc2.utils.FileBasedImageObjectArrayCollection_test')
improc2.utils.FileBasedImageObjectArrayCollection_test;
display('improc2.utils.findChannelsWithProcessorsOfRequiredType_test')
improc2.utils.findChannelsWithProcessorsOfRequiredType_test;
display('improc2.utils.FixedColumnsVariableRowsRectangleArrayPositionCalculator_test')
improc2.utils.FixedColumnsVariableRowsRectangleArrayPositionCalculator_test;
display('improc2.utils.FixedContrastSettings_test')
improc2.utils.FixedContrastSettings_test;
display('improc2.utils.formatStringsToTwoColumn_test')
improc2.utils.formatStringsToTwoColumn_test;
display('improc2.utils.getCenterOfConnectedBWImage_test')
improc2.utils.getCenterOfConnectedBWImage_test;
display('improc2.utils.getCentersOfImageObjectsInCurrentArray_test')
improc2.utils.getCentersOfImageObjectsInCurrentArray_test;
display('improc2.utils.getXandYPositionsAtEveryPixelInImage_test')
improc2.utils.getXandYPositionsAtEveryPixelInImage_test;
display('improc2.utils.GroupedCentroidsDisplayer_test')
improc2.utils.GroupedCentroidsDisplayer_test;
display('improc2.utils.Grouper_test')
improc2.utils.Grouper_test;
display('improc2.utils.HandleToLegacyimage_object_test')
improc2.utils.HandleToLegacyimage_object_test;
display('improc2.utils.IdentityContraster_test')
improc2.utils.IdentityContraster_test;
display('improc2.utils.ImageDisplayer_test')
improc2.utils.ImageDisplayer_test;
display('improc2.utils.ImageFromProcessorDataHolder_test')
improc2.utils.ImageFromProcessorDataHolder_test;
display('improc2.utils.ImageHolderFromImageObjectHandle_test')
improc2.utils.ImageHolderFromImageObjectHandle_test;
display('improc2.utils.ImageObjectArrayCollectionNavigator_test')
improc2.utils.ImageObjectArrayCollectionNavigator_test;
display('improc2.utils.ImageObjectDataFiles_test')
improc2.utils.ImageObjectDataFiles_test;
display('improc2.utils.ImageObjectScaledImageSliceHolder_test')
improc2.utils.ImageObjectScaledImageSliceHolder_test;
display('improc2.utils.ImageObjectsCentroidsSource_test')
improc2.utils.ImageObjectsCentroidsSource_test;
display('improc2.utils.ImageObjectsGroupings_test')
improc2.utils.ImageObjectsGroupings_test;
display('improc2.utils.ImageSizeAdaptiveViewportHolder_test')
improc2.utils.ImageSizeAdaptiveViewportHolder_test;
display('improc2.utils.InMemoryObjectArrayCollection_test')
improc2.utils.InMemoryObjectArrayCollection_test;
display('improc2.utils.loadCollectionIntoMemory_test')
improc2.utils.loadCollectionIntoMemory_test;
display('improc2.utils.MaskDisplayer_test')
improc2.utils.MaskDisplayer_test;
display('improc2.utils.MaskProviderFromCroppedMaskProvider_test')
improc2.utils.MaskProviderFromCroppedMaskProvider_test;
display('improc2.utils.MasksImageForAllObjectsInArray_test')
improc2.utils.MasksImageForAllObjectsInArray_test;
display('improc2.utils.MaxSettingContraster_test')
improc2.utils.MaxSettingContraster_test;
display('improc2.utils.methodsWithoutSuperClassMethods_test')
improc2.utils.methodsWithoutSuperClassMethods_test;
display('improc2.utils.MultiModeContraster_test')
improc2.utils.MultiModeContraster_test;
display('improc2.utils.NamedValuesAndChoicesFromItemCollection_test')
improc2.utils.NamedValuesAndChoicesFromItemCollection_test;
display('improc2.utils.NavigationKeyboardInterpreter_test')
improc2.utils.NavigationKeyboardInterpreter_test;
display('improc2.utils.NotifyingViewportHolder_test')
improc2.utils.NotifyingViewportHolder_test;
display('improc2.utils.NumberOfObjectsInArrayTextBox_test')
improc2.utils.NumberOfObjectsInArrayTextBox_test;
display('improc2.utils.NumSpotsTextBox_test')
improc2.utils.NumSpotsTextBox_test;
display('improc2.utils.ObjectHolder_test')
improc2.utils.ObjectHolder_test;
display('improc2.utils.ObjectNumberTextBox_test')
improc2.utils.ObjectNumberTextBox_test;
display('improc2.utils.PolygonAddableFromPolygonGrouper_test')
improc2.utils.PolygonAddableFromPolygonGrouper_test;
display('improc2.utils.PolygonBasedCentroidsGrouper_test')
improc2.utils.PolygonBasedCentroidsGrouper_test;
display('improc2.utils.ProcessorDataHolder_test')
improc2.utils.ProcessorDataHolder_test;
display('improc2.utils.ProcessorRegistrarForLegacyimage_object_test')
improc2.utils.ProcessorRegistrarForLegacyimage_object_test;
display('improc2.utils.scale_test')
improc2.utils.scale_test;
display('improc2.utils.setThresholdBasedOnAxesPosition_test')
improc2.utils.setThresholdBasedOnAxesPosition_test;
display('improc2.utils.SliceExcluderForRegionalMaxProcData_test')
improc2.utils.SliceExcluderForRegionalMaxProcData_test;
display('improc2.utils.SpotsDisplayer_test')
improc2.utils.SpotsDisplayer_test;
display('improc2.utils.SpotsProviderFromProcessorDataHolder_test')
improc2.utils.SpotsProviderFromProcessorDataHolder_test;
display('improc2.utils.subsetFiles_test')
improc2.utils.subsetFiles_test;
display('improc2.utils.suppressNeedsUpdateWarning_test')
improc2.utils.suppressNeedsUpdateWarning_test;
display('improc2.utils.TypeCheckedItemCollectionExtender_test')
improc2.utils.TypeCheckedItemCollectionExtender_test;
display('improc2.utils.UISynchronizedNamedValuesAndChoices_test')
improc2.utils.UISynchronizedNamedValuesAndChoices_test;
display('improc2.utils.validateAndFormatChannelNamesArgument_test')
improc2.utils.validateAndFormatChannelNamesArgument_test;
display('improc2.utils.ZSlicer_test')
improc2.utils.ZSlicer_test;
display('improc2.addAnnotationItemsToAllObjects_test')
improc2.addAnnotationItemsToAllObjects_test;
display('improc2.AnnotationsAdder_test')
improc2.AnnotationsAdder_test;
display('improc2.aTrousFilterParams_test')
improc2.aTrousFilterParams_test;
display('improc2.DataChangeTrackedProcStack_test')
improc2.DataChangeTrackedProcStack_test;
display('improc2.Describeable_test')
improc2.Describeable_test;
display('improc2.ImageDisplayer_test')
improc2.ImageDisplayer_test;
display('improc2.ImageObject_test')
improc2.ImageObject_test;
display('improc2.ImageObjectAnnotationsHandle_test')
improc2.ImageObjectAnnotationsHandle_test;
display('improc2.ImageObjectAnnotationsHolder_test')
improc2.ImageObjectAnnotationsHolder_test;
display('improc2.ImageObjectHandle_test')
improc2.ImageObjectHandle_test;
display('improc2.ImageObjectIterator_test')
improc2.ImageObjectIterator_test;
display('improc2.InteractiveFactor_test')
improc2.InteractiveFactor_test;
display('improc2.InteractiveLogical_test')
improc2.InteractiveLogical_test;
display('improc2.InteractiveNumeric_test')
improc2.InteractiveNumeric_test;
display('improc2.InteractiveString_test')
improc2.InteractiveString_test;
display('improc2.launchAnnotationsGUI_test')
improc2.launchAnnotationsGUI_test;
display('improc2.launchDataExtractor_test')
improc2.launchDataExtractor_test;
display('improc2.launchImageObjectBrowsingTools_test')
improc2.launchImageObjectBrowsingTools_test;
display('improc2.launchImageObjectTools_test')
improc2.launchImageObjectTools_test;
display('improc2.launchObjectGroupingGUI_test')
improc2.launchObjectGroupingGUI_test;
display('improc2.launchQuickGUI_test')
improc2.launchQuickGUI_test;
display('improc2.launchThresholdGUI_test')
improc2.launchThresholdGUI_test;
display('improc2.Legacyimage_objectAnnotationsHandle_test')
improc2.Legacyimage_objectAnnotationsHandle_test;
display('improc2.LoadSafeDataChangeStatus_test')
improc2.LoadSafeDataChangeStatus_test;
display('improc2.ManagedProcessorQueue_test')
improc2.ManagedProcessorQueue_test;
display('improc2.ManagedProcQueueRunner_test')
improc2.ManagedProcQueueRunner_test;
display('improc2.MaskFindingProc_test')
improc2.MaskFindingProc_test;
display('improc2.MultiChannelProcManager_test')
improc2.MultiChannelProcManager_test;
display('improc2.NavigatorGUI_test')
improc2.NavigatorGUI_test;
display('improc2.ParamList_test')
improc2.ParamList_test;
display('improc2.ProcessorRegistrar_test')
improc2.ProcessorRegistrar_test;
display('improc2.ProcessorStack_test')
improc2.ProcessorStack_test;
display('improc2.RemembersRunAndDataChange_test')
improc2.RemembersRunAndDataChange_test;
display('improc2.SingleChannelProcManager_test')
improc2.SingleChannelProcManager_test;
display('improc2.ThresholdPlotPlugin_test')
improc2.ThresholdPlotPlugin_test;
display('improc2.TypeCheckedFactor_test')
improc2.TypeCheckedFactor_test;
display('improc2.TypeCheckedLogical_test')
improc2.TypeCheckedLogical_test;
display('improc2.TypeCheckedNumeric_test')
improc2.TypeCheckedNumeric_test;
display('improc2.TypeCheckedString_test')
improc2.TypeCheckedString_test;
display('improc2.TypeCheckedYesNoOrNA_test')
improc2.TypeCheckedYesNoOrNA_test;
