display('improc2.dataNodes.buildMinimalImageObjectGraph_test')
improc2.dataNodes.buildMinimalImageObjectGraph_test;
display('improc2.dataNodes.ChannelStackContainer_test')
improc2.dataNodes.ChannelStackContainer_test;
display('improc2.dataNodes.DapiProcessedData_test')
improc2.dataNodes.DapiProcessedData_test;
display('improc2.dataNodes.DirectedAcyclicGraph_test')
improc2.dataNodes.DirectedAcyclicGraph_test;
display('improc2.dataNodes.GraphBasedImageObject_test')
improc2.dataNodes.GraphBasedImageObject_test;
display('improc2.dataNodes.HandleToGraphBasedImageObject_test')
improc2.dataNodes.HandleToGraphBasedImageObject_test;
display('improc2.dataNodes.ImageObjectBaseData_test')
improc2.dataNodes.ImageObjectBaseData_test;
display('improc2.dataNodes.Node_test')
improc2.dataNodes.Node_test;
display('improc2.dataNodes.ProcessorRegistrarForGraphBasedImageObject_test')
improc2.dataNodes.ProcessorRegistrarForGraphBasedImageObject_test;
