function Hs = layOutGUI(channels)
    backgColor = [0.247 0.247 0.247];
    
    
%     Hs.figA = figure('Position',[300 100 500 500],...
%         'NumberTitle','off',...
%         'Name','improc2.ManualSpotGUI.imageViewer',...
%         'Resize','on',...
%         'Toolbar','none',...
%         'MenuBar','none',...
%         'Color',backgColor,...
%         'Visible','off');
%     imgPanel = uipanel('Parent', Hs.figA, ...
%     'Units','normalized',...
%     'Position',[0 0.2 1 0.75],...
%     'BorderType', 'none', ...
%     'BackgroundColor',backgColor);
% 
%     Hs.imgAx = axes('Parent', imgPanel);
%     
%     axis(Hs.imgAx, 'equal');
    
%     Hs.addPointsButtonHandle = uicontrol('Style', 'pushbutton', ...
%     'Parent', Hs.figA, ...
%     'Units', 'normalized', ...
%     'Position', [0.05 0 0.2 0.1], ...
%     'String','add points');
% 
%     Hs.deselectAllButtonHandle = uicontrol('Style', 'pushbutton', ...
%     'Parent', Hs.figA, ...    
%     'Units', 'normalized', ...
%     'Position', [0.3 0 0.2 0.1], ...
%     'String','deselect all');
% 
%     Hs.deletePointsButtonHandle = uicontrol('Style', 'pushbutton', ...
%     'Parent', Hs.figA, ...
%     'Units', 'normalized', ...
%     'Position', [0.55 0 0.2 0.1], ...
%     'String', 'delete selected');
    
    
    
    
    Hs.figH = figure('Position',[650 100 255 500],...
        'NumberTitle','off',...
        'Name','improc2.ManualSpotGUI.channelControlPanel',...
        'Resize','on',...
        'Toolbar','none',...
        'MenuBar','none',...
        'Color',backgColor,...
        'Visible','off');
    
    set(Hs.figH, 'Visible', 'on');
    
    Hs.channelControlPanel  = uipanel('Parent',Hs.figH,...
        'Units','normalized',...
        'Position',[0 0.3889 1 0.3889],...
        'BorderType', 'none', ...
        'BackgroundColor',backgColor);
  
    Hs.displayText = uicontrol('Parent',Hs.figH,...
        'Style','text',...
        'Units','normalized',...
        'BackgroundColor',backgColor,...
        'ForegroundColor',[1 1 1], ...
        'Position',[0.15 0.85 0.2 0.0444],...
        'String','Display:','FontSize',12);
    
    for j = 1:length(channels)
        name = [(channels{j}) '_circlenumber'];
    Hs.(name) = uicontrol('Parent',Hs.figH,...
        'Style','edit',...
        'Units','normalized',...
        'BackgroundColor',[1 1 1],...
        'ForegroundColor',backgColor, ...
        'Position',[0.65 0.8889-(j*0.1) 0.1 0.0444],...
        'FontSize',12,...
        'String',0);
    end
    
    channels = [channels 'dapi' 'trans'];
    for j = 1:length(channels)
        name = [(channels{j}) '_text'];
    Hs.(name) = uicontrol('Parent',Hs.figH,...
        'Style','text',...
        'Units','normalized',...
        'BackgroundColor',backgColor,...
        'ForegroundColor',[1 1 1], ...
        'Position',[0.001 0.8889-(j*0.1) 0.2 0.0444],...
        'String',(channels{j}),'FontSize',12);
    end
    for j = 1:length(channels)
        name = [(channels{j}) '_display'];
    Hs.(name) = uicontrol('Parent',Hs.figH,...
        'Style','checkbox',...
        'Units','normalized',...
        'BackgroundColor',backgColor,...
        'ForegroundColor',[1 1 1], ...
        'Position',[0.2 0.8889-(j*0.1) 0.1 0.0444],...
        'FontSize',12);
    end
    for j = 1:length(channels)
        name = [(channels{j}) '_color'];
    Hs.(name) = uicontrol('Parent',Hs.figH,...
        'Style','edit',...
        'Units','normalized',...
        'BackgroundColor',[1 1 1],...
        'ForegroundColor',backgColor, ...
        'Position',[0.4 0.8889-(j*0.1) 0.2 0.0444],...
        'String','Choose Color','FontSize',12);
    end

    for j = 1:length(channels)
        name = [(channels{j}) '_scale'];
    Hs.(name) = uicontrol('Parent',Hs.figH,...
        'Style','edit',...
        'Units','normalized',...
        'BackgroundColor',[1 1 1],...
        'ForegroundColor',backgColor, ...
        'Position',[0.8 0.8889-(j*0.1) 0.1 0.0444],...
        'FontSize',12,...
        'String', 1);
    end
    
        Hs.circlebox = uicontrol('Parent',Hs.figH,...
        'Style','text',...
        'Units','normalized',...
        'BackgroundColor',backgColor,...
        'ForegroundColor',[1 1 1], ...
        'Position',[0.6 0.85 0.2 0.0444],...
        'String','Circle top:','FontSize',12);
    
            Hs.circlebox = uicontrol('Parent',Hs.figH,...
        'Style','text',...
        'Units','normalized',...
        'BackgroundColor',backgColor,...
        'ForegroundColor',[1 1 1], ...
        'Position',[0.8 0.85 0.2 0.0444],...
        'String','Manual Scale:','FontSize',12);


% 
%     Hs.channelDisplayText = uicontrol('Parent',Hs.figH,...
%         'Style','text',...
%         'Units','normalized',...
%         'Position',[0.01 0.95 0.39 0.0444],...
%         'BackgroundColor',backgColor,...
%         'ForegroundColor',[1 1 1], ...
%         'String','this is where the channel selection stuff will go','FontSize',12);
%     
    
    Hs.lowerFreeArea = uipanel('Parent',Hs.figH,...
        'Units','normalized',...
        'BorderType', 'none', ...
        'Position',[0.0345 0 0.9404 0.12],...
        'BackgroundColor',backgColor);
    
    Hs.naviPanel  = uipanel('Parent',Hs.figH,...
        'Units','normalized',...
        'Position',[0.0345 0.05 0.9404 0.2249],...
        'BackgroundColor',[0.929 0.929 0.929]);
    Hs.goodCheck = uicontrol('Parent',Hs.naviPanel,...
        'Style','checkbox',...
        'Units','normalized',...
        'Position',[0.05 0.7663 0.4030 0.2262],...
        'String','Good Object',...
        'Value',0);
    Hs.prevObj = uicontrol('Parent',Hs.naviPanel,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',[0.5250 0.5275 0.2160 0.400],...
        'String','Prev',...
        'FontSize',12,'FontWeight','bold');
    Hs.nextObj = uicontrol('Parent',Hs.naviPanel,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',[0.7580 0.5275 0.2160 0.400],...
        'String','Next',...
        'FontSize',12,'FontWeight','bold');
    
    Hs.countsLabel = uicontrol('Parent',Hs.naviPanel,'Style','text',...
        'String','#Manually Chosen Spots:',...
        'Units','normalized',...
        'Position',[0.0500 0.5375 0.2000 0.1962],...
        'FontSize',12,'FontWeight','bold');
    Hs.countsDisplay = uicontrol('Parent',Hs.naviPanel,'Style','text',...
        'String','0',...
        'Units','normalized',...
        'Position',[0.2500 0.5375 0.2500 0.1962],...
        'FontSize',12,'FontWeight','bold');
    
    Hs.fileLabel = uicontrol('Parent', Hs.naviPanel, ...
        'Style','text',...
        'String',sprintf('File:\n/ '),...
        'Units', 'normalized', ...
        'Position', [0.0250 0.1250 0.2160 0.3125], ...
        'FontSize', 12, 'FontWeight', 'bold');
    Hs.goToArray = uicontrol('Parent',Hs.naviPanel,...
        'Style','edit',...
        'Units','normalized',...
        'Position',[0.2750 0.1250 0.2160 0.3125],...
        'FontSize',12);
    Hs.objectLabel = uicontrol('Parent', Hs.naviPanel, ...
        'Style','text',...
        'String',sprintf('Obj:\n/ '),...
        'Units', 'normalized', ...
        'Position', [0.5250 0.1250 0.2160 0.3125], ...
        'FontSize', 12, 'FontWeight', 'bold');
    Hs.goToObj = uicontrol('Parent',Hs.naviPanel,...
        'Style','edit',...
        'Units','normalized',...
        'Position',[0.7750 0.1250 0.2160 0.3125],...
        'FontSize',12);
   
%     set(Hs.figA, 'Visible', 'on');
    
end

