function [Hs] = layOutImageInspectionGUI()
    
    backgColor = [0.247 0.247 0.247];
    
    Hs.figH = figure('Position',[200 100 450 500],...
        'NumberTitle','off',...
        'Name','improc2.ManualSpotGUI.ImageViewer',...
        'Resize','on',...
        'Toolbar','none',...
        'MenuBar','none',...
        'Color',backgColor,...
        'Visible','off');
    
    set(Hs.figH, 'Visible', 'on');
    
    Hs.imgAx = axes('Parent',Hs.figH,...
        'Units','normalized',...
        'Position',[0.01, 0.105, 0.98, .890],...
        'XTick',[],'YTick',[]);
    axis(Hs.imgAx, 'equal');
    
    Hs.checkBoxPanel = uipanel('Parent',Hs.figH,...
        'Units','normalized',...
        'Position',[0.005 0.005 0.990 0.1],...
        'BackgroundColor',backgColor, ...
        'BorderType', 'none');

    Hs.addPointsButtonHandle  = uicontrol('Parent',Hs.checkBoxPanel,...
        'Style','pushbutton',...
        'Units','normalized',...
        'ForegroundColor',backgColor, ...
        'BackgroundColor',[1 1 1],...
        'Position',[0.005 0.015 0.33 1],...
        'String','add point','FontSize',12);
    Hs.deselectAllButtonHandle  = uicontrol('Parent',Hs.checkBoxPanel,...
        'Style','pushbutton',...
        'Units','normalized',...
        'ForegroundColor',backgColor, ...
        'BackgroundColor',[1 1 1],...
        'Position',[0.335 0.015 0.33 1],...
        'String','unselect points','FontSize',12);
    Hs.deletePointsButtonHandle  = uicontrol('Parent',Hs.checkBoxPanel,...
        'Style','pushbutton',...
        'Units','normalized',...
        'ForegroundColor',backgColor, ...
        'BackgroundColor',[1 1 1],...
        'Position',[0.665 0.015 0.33 1],...
        'String','delete last point','FontSize',12);

end
