function addImageAndThumbnailInteractions(resources)
    
    gui = resources.gui;
    displaySubsystem = resources.displaySubsystem;
    deletionsUISubsystem = resources.deletionsUISubsystem;
    
    
    imageZoomer = dentist.utils.ImageZoomingMouseInterpreter(displaySubsystem);
    imagePanner = dentist.utils.ImagePanningMouseInterpreter(displaySubsystem);
    
    buttonStruct = struct(...
        'zoom', gui.zoomButton, ...
        'pan', gui.dragButton, ...
        'delete', gui.drawButton ...
        );
    actionOnSelect = struct(...
        'zoom', @() imageZoomer.wireToFigureAndAxes(gui.figH, gui.imgAx), ...
        'pan', @() imagePanner.wireToFigureAndAxes(gui.figH, gui.imgAx), ...
        'delete', @deletionsUISubsystem.enable ...
        );
    actionOnDeselect = struct(...
        'zoom', @imageZoomer.unwire, ...
        'pan', @imagePanner.unwire, ...
        'delete', @deletionsUISubsystem.disable ...
        );
    
    
    zoomPanDeleteToggler = dentist.utils.FunctionExecutingToggleGroup(...
        buttonStruct, actionOnSelect, actionOnDeselect);
    
    zoomPanDeleteToggler.initialize('zoom');
    
    
    thumbnailPanner = dentist.utils.ThumbnailPanningMouseInterpreter(displaySubsystem);
    thumbnailPanner.wireToFigureAndAxes(gui.figH, gui.thumbAx);
    
end

