function displaySubsystem = buildImageSubsystem(resources)
    
    gui                         = resources.gui;
    imageProvider               = resources.imageProvider;
    spotsAndCentroids           = resources.spotsAndCentroids;
    channelHolder               = resources.channelHolder;
    numSpotsToColorTranslators  = resources.numSpotsToColorTranslators;
    centroidRadiusPixels        = resources.centroidRadiusPixels;
    zoomTransitionFineToMedium  = resources.zoomTransitionFineToMedium;
    zoomTransitionMediumToWide  = resources.zoomTransitionMediumToWide;
    thumbnails                  = resources.thumbnails;
    
    initialViewport = dentist.utils.TileAwareImageViewport(imageProvider);
    viewportHolder = dentist.utils.ViewportHolder(initialViewport);
    
    
    centroidsParametersHolder = dentist.utils.CentroidsDisplayerParametersHolder();
    centroidsParametersHolder.set('circleRadius', centroidRadiusPixels)
    
    centroidsDisplayerResources = struct();
    centroidsDisplayerResources.centroidsAndNumSpotsSource  = spotsAndCentroids;
    centroidsDisplayerResources.parametersHolder            = centroidsParametersHolder;
    centroidsDisplayerResources.viewportHolder              = viewportHolder;
    centroidsDisplayerResources.channelHolder               = channelHolder;
    centroidsDisplayerResources.numSpotsToColorTranslators  = numSpotsToColorTranslators;
    
    coreCentroidsDisplayer = dentist.utils.CentroidsDisplayer(...
        gui.imgAx, centroidsDisplayerResources);
    centroidsDisplayer = ...
        dentist.utils.VisibilityToggleableDisplayer(coreCentroidsDisplayer);
    centroidsDisplayer.attachVisibilityUIControl(gui.centroidsCheck);
    
    coreSpotsDisplayer = dentist.utils.SpotsDisplayer(...
        gui.imgAx, spotsAndCentroids, channelHolder, viewportHolder);
    spotsDisplayer = ...
        dentist.utils.VisibilityToggleableDisplayer(coreSpotsDisplayer);
    spotsDisplayer.attachVisibilityUIControl(gui.spotsCheck);
    
    numSpotsParametersHolder = dentist.utils.CentroidsNumSpotsParametersHolder();
    coreNumSpotsDisplayer = dentist.utils.CentroidsNumSpotsTextDisplayer(...
        gui.imgAx, spotsAndCentroids, ...
        channelHolder, numSpotsParametersHolder, viewportHolder);
    numSpotsDisplayer = ...
        dentist.utils.VisibilityToggleableDisplayer(coreNumSpotsDisplayer);
    numSpotsDisplayer.attachVisibilityUIControl(gui.numSpotsCheck);
    
    tiledImageDisplayer = dentist.utils.TiledImageDisplayer(...
        gui.imgAx, imageProvider, channelHolder, viewportHolder);
    
    level1NumSpotsDisplayer = dentist.utils.ModifiedDisplayer(...
        numSpotsDisplayer, numSpotsParametersHolder, ...
        'FontSize', 16, 'xOffset', -10, 'yOffset', 5);
    level2NumSpotsDisplayer = dentist.utils.ModifiedDisplayer(...
        numSpotsDisplayer, numSpotsParametersHolder, ...
        'FontSize', 8, 'xOffset', -37, 'yOffset', 5);
    level3NumSpotsDisplayer = dentist.utils.ModifiedDisplayer(...
        numSpotsDisplayer, numSpotsParametersHolder, ...
        'FontSize', 8, 'xOffset', -10, 'yOffset', 5);
    
    level2CentroidsDisplayer = dentist.utils.ModifiedDisplayer(...
        centroidsDisplayer, centroidsParametersHolder, ...
        'spotsOrCircles', 'circles');
    level3CentroidsDisplayer = dentist.utils.ModifiedDisplayer(...
        centroidsDisplayer, centroidsParametersHolder, ...
        'spotsOrCircles', 'spots');
    
    axisSetter = dentist.utils.AxisSetDisplayer(gui.imgAx, viewportHolder);
    
    level1Displayer = dentist.utils.DisplayerSequence(...
        tiledImageDisplayer, ...
        spotsDisplayer, ...
        level1NumSpotsDisplayer);
    
    level2Displayer = dentist.utils.DisplayerSequence(...
        axisSetter, ...
        level2CentroidsDisplayer, ...
        level2NumSpotsDisplayer);
    
    level3Displayer = dentist.utils.DisplayerSequence(...
        axisSetter, ...
        level3CentroidsDisplayer, ...
        level3NumSpotsDisplayer);
    
    
    widthOrHeightAtZoomTransitions = ...
        [zoomTransitionFineToMedium, zoomTransitionMediumToWide];
    mainDisplayer = dentist.utils.MultiZoomLevelImageDisplayer(...
        viewportHolder, widthOrHeightAtZoomTransitions, ...
        level1Displayer, level2Displayer, level3Displayer);
    
    thumbnailDisplayer = dentist.utils.ThumbnailDisplayer(...
        gui.thumbAx, thumbnails, channelHolder, viewportHolder,...
        'EdgeColor', 'w');
    
    
    displaySubsystem = dentist.ImageDisplaySubsystem(viewportHolder, ...
        mainDisplayer, thumbnailDisplayer);
    
    displaySubsystem.setViewport(initialViewport);
    
end

