dentist.tests.cleanupForTests;

Hs = dentist.createAndLayOutMainGUI();
assert(ishandle(Hs.figH))
assert(strcmp(get(Hs.figH, 'Renderer'), 'zbuffer'))
assert(ishandle(Hs.imgAx))
assert(ishandle(Hs.thumbAx))
assert(ishandle(Hs.thresholdAx))
assert(ishandle(Hs.thresholdL))
assert(ishandle(Hs.resetThresh))
assert(ishandle(Hs.figTitle))
assert(ishandle(Hs.centList))
assert(ishandle(Hs.centroidsCheck))
assert(ishandle(Hs.numSpotsCheck))
assert(ishandle(Hs.spotsCheck))
assert(ishandle(Hs.filterButton))
assert(ishandle(Hs.filterCheckBox))
assert(ishandle(Hs.chanPop))
assert(ishandle(Hs.zoomButton))
assert(ishandle(Hs.dragButton))
assert(ishandle(Hs.drawButton))
assert(ishandle(Hs.saveButton))
assert(ishandle(Hs.viewButton))
assert(ishandle(Hs.histButton))
assert(ishandle(Hs.locationButton))
assert(ishandle(Hs.drawPanel))
assert(ishandle(Hs.undoButton))
assert(ishandle(Hs.resetButton))
assert(ishandle(Hs.makeThumbnailsButton))
