function Td = createAndLayOutFilterGUI(channelNames)

    Td.figH = figure('Position',[400 150 400 405],...
        'NumberTitle','off',...
        'Name','Set Filter',...
        'Resize','off',...
        'Toolbar','none',...
        'MenuBar','none',...
        'HandleVisibility', 'callback',...
        'Color',[0.247 0.247 0.247],...
        'Visible','on');
    
    position = 0.85;
    chanIndex = 1;
    leftNumBoxes = dentist.utils.ChannelArray(channelNames);
    rightNumBoxes = dentist.utils.ChannelArray(channelNames);
    
    for index = 1:numel(channelNames)
        channelName = channelNames{index};
        chanPanel = uipanel('Parent',Td.figH,...
            'Units','normalized',...
            'BorderType','etchedin',...
            'BackgroundColor',[0.247 0.247 0.247],...
            'Visible','on',...
            'Position',[0.05,position,0.90,0.1]);
        chanLabel = uicontrol('Parent',chanPanel,...
            'Style','text',...
            'String',channelName,'FontSize',14,...
            'HorizontalAlignment','Left',...
            'Units','normalized',...
            'Position',[0.025 0.1 0.2 0.8],...
            'ForegroundColor',[1 1 1],...
            'BackgroundColor',[0.247 0.247 0.247]);
        leftNumBox  = uicontrol('Parent',chanPanel,...
            'String','',...
            'Style','edit',...
            'FontSize',10,...
            'HorizontalAlignment','Left',...
            'Units','normalized',...
            'Position',[0.3 0.1 0.2 0.8],...
            'BackgroundColor',[1 1 1]);
        leftNumBoxes = leftNumBoxes.setByChannelName(leftNumBox, channelName);
        lessGreater = uicontrol('Parent',chanPanel,...
            'Style','text',...
            'String','< Counts < ','FontSize',10,...
            'HorizontalAlignment','Left',...
            'Units','normalized',...
            'Position',[0.515 0.3 0.225 0.4],...
            'ForegroundColor',[1 1 1],...
            'BackgroundColor',[0.247 0.247 0.247]);
        rightNumBox  = uicontrol('Parent',chanPanel,...
            'String','',...
            'Style','edit',...
            'FontSize',10,...
            'HorizontalAlignment','Left',...
            'Units','normalized',...
            'Position',[0.750 0.1 0.2 0.8],...
            'BackgroundColor',[1 1 1]);
        rightNumBoxes = rightNumBoxes.setByChannelName(rightNumBox, channelName);
        position = position - 0.12;
        chanIndex = chanIndex + 1;
    end
    Td.leftNumBoxes = leftNumBoxes;
    Td.rightNumBoxes = rightNumBoxes;
    Td.applyFilter  = uicontrol('Parent',Td.figH,...
        'String','Apply Filter',...
        'Style','pushbutton',...
        'FontSize',10,...
        'HorizontalAlignment','Left',...
        'Units','normalized',...
        'Position',[0.05 (position + .03) 0.3 0.07],...
        'BackgroundColor',[1 1 1]);
