% display('dentist.legacy.getLayoutOrientation_test')
% dentist.legacy.getLayoutOrientation_test;
display('dentist.shift.process.generateCanvases_test')
dentist.shift.process.generateCanvases_test;
display('dentist.shift.process.getGridAndTileSize_test')
dentist.shift.process.getGridAndTileSize_test;
display('dentist.shift.AxesManager_test')
dentist.shift.AxesManager_test;
display('dentist.shift.ImageProvider_test')
dentist.shift.ImageProvider_test;
display('dentist.shift.MouseGestureInterpreter_test')
dentist.shift.MouseGestureInterpreter_test;
display('dentist.utils.asRowAndColumn_test')
dentist.utils.asRowAndColumn_test;
display('dentist.utils.assignSpotsToCentroids_test')
dentist.utils.assignSpotsToCentroids_test;
display('dentist.utils.AxisSetDisplayer_test')
dentist.utils.AxisSetDisplayer_test;
display('dentist.utils.blowUpPixels_test')
dentist.utils.blowUpPixels_test;
display('dentist.utils.buildFilePathsGrid_test')
dentist.utils.buildFilePathsGrid_test;
display('dentist.utils.CellArrayCyclicIterator_test')
dentist.utils.CellArrayCyclicIterator_test;
display('dentist.utils.CentroidListBoxController_test')
dentist.utils.CentroidListBoxController_test;
display('dentist.utils.Centroids_test')
dentist.utils.Centroids_test;
display('dentist.utils.CentroidsDisplayer_test')
dentist.utils.CentroidsDisplayer_test;
display('dentist.utils.CentroidsDisplayerParametersHolder_test')
dentist.utils.CentroidsDisplayerParametersHolder_test;
display('dentist.utils.CentroidsFilter_test')
dentist.utils.CentroidsFilter_test;
display('dentist.utils.CentroidsNumSpotsParametersHolder_test')
dentist.utils.CentroidsNumSpotsParametersHolder_test;
display('dentist.utils.CentroidsNumSpotsTextDisplayer_test')
dentist.utils.CentroidsNumSpotsTextDisplayer_test;
display('dentist.utils.ChannelArray_test')
dentist.utils.ChannelArray_test;
display('dentist.utils.ChannelSwitchCoordinator_test')
dentist.utils.ChannelSwitchCoordinator_test;
display('dentist.utils.ColoringAndThumbnailSettings_test')
dentist.utils.ColoringAndThumbnailSettings_test;
display('dentist.utils.computeTiledImageWidthAndHeight_test')
dentist.utils.computeTiledImageWidthAndHeight_test;
display('dentist.utils.DeleteableSpotsAndCentroids_test')
dentist.utils.DeleteableSpotsAndCentroids_test;
display('dentist.utils.DeletionsUIControlsEnabler_test')
dentist.utils.DeletionsUIControlsEnabler_test;
display('dentist.utils.DisplayerSequence_test')
dentist.utils.DisplayerSequence_test;
display('dentist.utils.filterPointsByViewport_test')
dentist.utils.filterPointsByViewport_test;
display('dentist.utils.findIndicesOfTileInTilingImage_test')
dentist.utils.findIndicesOfTileInTilingImage_test;
display('dentist.utils.FreeHandDrawingInterpreter_test')
dentist.utils.FreeHandDrawingInterpreter_test;
display('dentist.utils.FunctionExecutingToggleGroup_test')
dentist.utils.FunctionExecutingToggleGroup_test;
display('dentist.utils.ImagePanningMouseInterpreter_test')
dentist.utils.ImagePanningMouseInterpreter_test;
display('dentist.utils.ImageProvider_test')
dentist.utils.ImageProvider_test;
display('dentist.utils.ImageViewport_test')
dentist.utils.ImageViewport_test;
display('dentist.utils.ImageZoomingMouseInterpreter_test')
dentist.utils.ImageZoomingMouseInterpreter_test;
display('dentist.utils.interpretLayoutTypeNumber_test')
dentist.utils.interpretLayoutTypeNumber_test;
display('dentist.utils.LineDrawingInterpreter_test')
dentist.utils.LineDrawingInterpreter_test;
display('dentist.utils.ModifiedDisplayer_test')
dentist.utils.ModifiedDisplayer_test;
display('dentist.utils.MouseGestureInterpreter_test')
dentist.utils.MouseGestureInterpreter_test;
display('dentist.utils.MultiZoomLevelImageDisplayer_test')
dentist.utils.MultiZoomLevelImageDisplayer_test;
display('dentist.utils.MutuallyExclusiveToggleGroup_test')
dentist.utils.MutuallyExclusiveToggleGroup_test;
display('dentist.utils.NotifyingDeleter_test')
dentist.utils.NotifyingDeleter_test;
display('dentist.utils.occurrencesOfIntegersUpToN_test')
dentist.utils.occurrencesOfIntegersUpToN_test;
display('dentist.utils.PolygonAddingMouseInterpreter_test')
dentist.utils.PolygonAddingMouseInterpreter_test;
display('dentist.utils.PolygonsBasedDeletionsTool_test')
dentist.utils.PolygonsBasedDeletionsTool_test;
display('dentist.utils.PolygonsDisplayer_test')
dentist.utils.PolygonsDisplayer_test;
display('dentist.utils.PolygonStack_test')
dentist.utils.PolygonStack_test;
display('dentist.utils.PositionAndChannelArray_test')
dentist.utils.PositionAndChannelArray_test;
display('dentist.utils.PositionArray_test')
dentist.utils.PositionArray_test;
display('dentist.utils.rasterizePoints_test')
dentist.utils.rasterizePoints_test;
display('dentist.utils.RectangleDrawingInterpreter_test')
dentist.utils.RectangleDrawingInterpreter_test;
display('dentist.utils.RemoveAllPolygonsButton_test')
dentist.utils.RemoveAllPolygonsButton_test;
display('dentist.utils.RemovePolygonButton_test')
dentist.utils.RemovePolygonButton_test;
display('dentist.utils.SpotFrequencyTable_test')
dentist.utils.SpotFrequencyTable_test;
display('dentist.utils.Spots_test')
dentist.utils.Spots_test;
display('dentist.utils.SpotsAndCentroids_test')
dentist.utils.SpotsAndCentroids_test;
display('dentist.utils.SpotsDisplayer_test')
dentist.utils.SpotsDisplayer_test;
display('dentist.utils.SpotsPassingThresholdAndCentroids_test')
dentist.utils.SpotsPassingThresholdAndCentroids_test;
display('dentist.utils.ThresholdPlotMouseInterpreter_test')
dentist.utils.ThresholdPlotMouseInterpreter_test;
display('dentist.utils.ThresholdPlotPlugin_test')
dentist.utils.ThresholdPlotPlugin_test;
display('dentist.utils.ThresholdsHolder_test')
dentist.utils.ThresholdsHolder_test;
display('dentist.utils.ThumbnailDisplayer_test')
dentist.utils.ThumbnailDisplayer_test;
display('dentist.utils.ThumbnailMaker_test')
dentist.utils.ThumbnailMaker_test;
display('dentist.utils.ThumbnailMakingFactory_test')
dentist.utils.ThumbnailMakingFactory_test;
display('dentist.utils.ThumbnailPanningMouseInterpreter_test')
dentist.utils.ThumbnailPanningMouseInterpreter_test;
display('dentist.utils.TileAwareImageViewport_test')
dentist.utils.TileAwareImageViewport_test;
display('dentist.utils.TiledImageDisplayer_test')
dentist.utils.TiledImageDisplayer_test;
display('dentist.utils.TileIterator_test')
dentist.utils.TileIterator_test;
display('dentist.utils.TilePosition_test')
dentist.utils.TilePosition_test;
display('dentist.utils.updateStruct_test')
dentist.utils.updateStruct_test;
display('dentist.utils.ValueToColorTranslator_test')
dentist.utils.ValueToColorTranslator_test;
display('dentist.utils.VisibilityToggleableDisplayer_test')
dentist.utils.VisibilityToggleableDisplayer_test;
display('dentist.utils.WaitBar_test')
dentist.utils.WaitBar_test;
display('dentist.CentroidsListBoxSubsystem_test')
dentist.CentroidsListBoxSubsystem_test;
display('dentist.createAndLayOutFilterGUI_test')
dentist.createAndLayOutFilterGUI_test;
display('dentist.createAndLayOutMainGUI_test')
dentist.createAndLayOutMainGUI_test;
display('dentist.findCentroidsInImage_test')
dentist.findCentroidsInImage_test;
display('dentist.findSpotsAndCentroidsAllTiles_test')
dentist.findSpotsAndCentroidsAllTiles_test;
display('dentist.findSpotsInTile_test')
dentist.findSpotsInTile_test;
display('dentist.ImageDisplaySubsystem_test')
dentist.ImageDisplaySubsystem_test;
display('dentist.launchGUI_test')
dentist.launchGUI_test;
