function [Hs] = layOutImageInspectionGUI()
    
    backgColor = [0.247 0.247 0.247];
    
    Hs.figH = figure('Position',[200 100 450 500],...
        'NumberTitle','off',...
        'Name','Drag, left/right/double click',...
        'Resize','on',...
        'Toolbar','none',...
        'MenuBar','none',...
        'Color',backgColor,...
        'Visible','off');
    
    set(Hs.figH, 'Visible', 'on');
    
    Hs.imgAx = axes('Parent',Hs.figH,...
        'Units','normalized',...
        'Position',[0.01, 0.105, 0.98, .890],...
        'XTick',[],'YTick',[]);
    axis(Hs.imgAx, 'equal');
    
    set(Hs.imgAx, 'YDir', 'reverse');
    
    Hs.checkBoxPanel = uipanel('Parent',Hs.figH,...
        'Units','normalized',...
        'Position',[0.505 0.005 0.490 0.1],...
        'BackgroundColor',backgColor, ...
        'BorderType', 'none');
    
    Hs.dapiCheck  = uicontrol('Parent',Hs.checkBoxPanel,...
        'Style','checkbox',...
        'Units','normalized',...
        'ForegroundColor',[1 1 1], ...
        'BackgroundColor',backgColor,...
        'Position',[0.005 0.005 0.49 0.49],...
        'String','DAPI','FontSize',12);
    Hs.transCheck = uicontrol('Parent',Hs.checkBoxPanel,...
        'Style','checkbox',...
        'Units','normalized',...
        'ForegroundColor',[1 1 1], ...
        'BackgroundColor',backgColor,...
        'Position',[0.505 0.005 0.49 0.49],...
        'String','Trans','FontSize',12);
    Hs.blobCheck  = uicontrol('Parent',Hs.checkBoxPanel,...
        'Style','checkbox',...
        'Units','normalized',...
        'ForegroundColor',[1 1 1], ...
        'BackgroundColor',backgColor,...
        'Position',[0.005 0.505 0.49 0.49],...
        'String','Blobs','FontSize',12);
    Hs.segmentCheck = uicontrol('Parent',Hs.checkBoxPanel,...
        'Style','checkbox',...
        'Units','normalized',...
        'ForegroundColor',[1 1 1], ...
        'BackgroundColor',backgColor,...
        'Position',[0.505 0.505 0.49 0.49],...
        'String','Segmentation','FontSize',12);
    
    Hs.contrastPanel = uipanel('Parent',Hs.figH,...
        'Title','Contrast',...
        'Units','normalized',...
        'Position',[0.005 0.005 0.490 0.1],...
        'BackgroundColor',[0.929 0.929 0.929]);
    Hs.thresholdContrastRadio = uicontrol('Parent',Hs.contrastPanel,...
        'Style','radiobutton',...
        'Units','normalized',...
        'Position',[0.009,0.179,0.346,0.857],...
        'HandleVisibility','off',...
        'String','Thresh.');
    Hs.fixedContrastRadio = uicontrol('Parent',Hs.contrastPanel,...
        'Style','radiobutton',...
        'Units','normalized',...
        'Position',[0.368,0.179,0.376,0.857],...
        'HandleVisibility','off',...
        'String','Fixed');
    Hs.fitContrastRadio = uicontrol('Parent',Hs.contrastPanel,...
        'Style','radiobutton',...
        'Units','normalized',...
        'Position',[0.709,0.179,0.286,0.857],...
        'HandleVisibility','off',...
        'String','FitToMax');
end
