improc2.tests.cleanupForTests;

existingtable = {'a',1,2;...
    'b',2,5;...
    'c','cake','pie'};
existingtable = existingtable';
inputrow = {'b',3;...
    'c','scone';...
    'd',true;...
    'e',3};
inputrow = inputrow';

outTable = improc2.utils.addRowToCellTable(existingtable,inputrow);

 
expected = {...
    'a',    'b',    'c' ,       'd',    'e';...
    [1],    [2],    'cake',      [],     [];...
    [2],    [5],    'pie' ,      [] ,    []; ...
     [],    [3] ,   'scone' ,   [1]  ,  [3]};
 
 assert(isequal(outTable, expected))