function channelNames = validateAndFormatChannelNamesArgument(channelNames)
    assert(~isempty(channelNames), ...
        'improc2:BadArguments', ...
        'channelNames should be a string or a cell array of strings')
    if ischar(channelNames)
        channelNames = {channelNames};
    end
    assert(iscell(channelNames) && all(cellfun(@ischar, channelNames)),...
        'improc2:BadArguments', ...
        'channelNames should be a string or a cell array of strings')
end
